### ISSUE TITLE
Xilinx Zynq Ultrascale+ Parts

### ISSUE THREAD

**Issue by KalahariGecko** [xesscorp/KiCad-Schematic-Symbol-Libraries#1]
Hello,
I cannot find the Zynq Ultrascale+ parts (XCZU9EG) in the ultrascale library (xilinxultra.lib).

**Comment by xesscorp** [comment]
Looks like Xilinx changed their format for the CSV pin files and a lot of the new FPGAs aren't getting into the library. I'll need to fix the Xilinx CSV reader routine and regenerate the libraries.

**Comment by KalahariGecko** [comment]
Thanks, I appreciate it, is there anything I can do to help?

**Comment by xesscorp** [comment]
I've updated the libraries. See if the devices you need are in there.

**Comment by KalahariGecko** [comment]
Thanks, the part I need is there.
